name: build
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'koyeb-community'
    steps:
      - uses: actions/checkout@v2
      - uses: koyeb-community/catalog-builder@master
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: koyeb-community/catalog-seed-action@master
        name: "Seed staging"
        with:
          api_username: ${{ secrets.API_USERNAME }}
          api_password: ${{ secrets.API_STAGING_PASSWORD }}
          api_url: "https://staging.koyeb.com"
